pointfreeco/swift-parsing

Package.swift

This fixes the following error:
error: 
```
'package(name:url:from:)' is unavailable
.package(name: "Benchmark", url: "https://github.com/google/swift-benchmark", from: "0.1.0"),
^~~~~~~
PackageDescription.Package.Dependency:5:24: note: 'package(name:url:from:)' was introduced in PackageDescription 5.2
public static func package(name: String? = nil, url: String, from version: PackageDescription.Version) -> PackageDescription.Package.Dependency
```
There might be a solution to this error that doesn't involve requiring Swift 5.2 but this is the easiest one. Let me know if you're ok with this fix ☺️.

Use SPM tools version 5.2

---

README.md

In both examples, "Hello,World" is parsed the same way, therefore the remainders should be equivalent.

Fix in documentation

---

Sources/Parsing/Parsers/Take.swift
Tests/ParsingTests/TakeTests.swift

This may not be advisable. Chaining more that 6 parsers results in a noticeable increase in compile time. At 11 parsers it can be around 20 seconds. At around 16 parsers the compiler gives up. I've written the tests in a way that reduces compile times.

Add Take parsers up to 11

---

Tests/ParsingTests/DoubleTests.swift

On my machine running Xcode 12.5, the test failed because it parsed `inf` instead of `nil`. I can't find in which version of Swift this behavior has changed, and I can't fence the code accordingly, but I guess this workaround still tests what matters.
I can happily close this PR if a better solution is found.

Fix testFloat() test

---

Sources/Parsing/Parsers/Int.swift
Tests/ParsingTests/DoubleTests.swift
Tests/ParsingTests/IntTests.swift

Fix for an issue discussed in https://github.com/pointfreeco/swift-parsing/discussions/36
Int parser should fail if a sign (-/+) is not followed by a digit.
Tests for Double and Float parsers are also added to prevent a possible introduction of this issue there in the future.
Note: I wanted to use `guard` for a check but both following examples didn't feel as straightforward as `if`:
```swift
guard !(parsedSign && length == 1) 
else { return nil }
```
```swift
guard !parsedSign || length != 1
else { return nil }
```

Int parser fix on just "-" or "+"

---

Package.resolved
Package.swift

Exposing the benchmark executable as a product makes its dependencies show up when depending on the package downstream. This means you'll see swift-argument-parser and swift-benchmark in your project when you depend on swift-parsing. By removing the product, these details should no longer be exposed downstream, and the benchmark still shows up just fine as an executable when working directly on swift-parsing.

Remove benchmark product

---

Sources/Parsing/Parsers/FirstWhere.swift

After seeing #48 come in it became clear that this parser is maybe not worth including in the library. First, its behavior is different than `Collection.first(where:)`, which "consumes" the collection till the first match, but our parser merely filters based on the first match. And so really, we could be explicit using existing operators:
- `First().filter(predicate)` for the existing behavior
- `Skip(Prefix(while: { !predicate($0) })).take(First())` for behavior similar to `Collection.first(where:)`

Deprecate `FirstWhere`

---

Package.resolved
Sources/Parsing/Parsers/Prefix.swift
Tests/ParsingTests/PrefixTests.swift

Another thing noticed by #48. I think our existing behavior wasn't quite right.

Prefix should match when maxLength < match.count

---

.github/workflows/ci.yml
Package.resolved
Package.swift
Sources/Parsing/Parsers/Double.swift

Global `cLocale` constant was broken on Windows and was actually unused, it made sense to remove it.
Additionally, I've expanded macOS Xcode version matrix to include 12.4, 12.5, and 13.0 for testing with different Swift versions. Now all Xcode version values are quoted, since YAML automatically parses `13.0` as a number not a string, converting it to plain `13`, which breaks the build.
For testing on Windows I'm `MaxDesiatov/swift-windows-action` which invokes `swift test` automatically, but let me know if you'd like that to be more explicit.

Fix Windows support, expand GHA platform coverage

---

.github/workflows/ci.yml
README.md
Sources/swift-parsing-benchmark/Bool.swift
Sources/swift-parsing-benchmark/CSV/CSVBenchmarks.swift
Sources/swift-parsing-benchmark/Color.swift
Sources/swift-parsing-benchmark/Date.swift
Sources/swift-parsing-benchmark/HTTP.swift
Sources/swift-parsing-benchmark/JSON.swift
Sources/swift-parsing-benchmark/Numerics.swift
Sources/swift-parsing-benchmark/Race.swift
Sources/swift-parsing-benchmark/UUID.swift

This work based on a discussion we had earlier. Our benchmarks were not quite real world in the sense that they worked with unsafe buffer pointers. While it might be a good idea to eke out every last bit of performance with an unsafe pointer, our benchmarks should maybe err on the side of typical library use instead. As a consequence, this PR also cleans up how these parsers are defined.

Clean up benchmarks

---

Sources/Parsing/Parsers/Double.swift
Tests/ParsingTests/DoubleTests.swift

After #66 came in I reread the existing logic and think it's maybe a bit too loose. It does its best to consume what it thinks may be a valid sub-sequence and then passes the result to `Double.init`.
I think we should be more careful what we pass to `Double.init`. Right now we allow for the following things to get passed over:
- `"-.1" -> -0.1`
This may not be problematic, but it's not even a valid Swift literal. Maybe we should be more strict and always require the integer when there's a fractional part?
- `"+1." -> 1.0`
This is more problematic: we consume the period, which may not be intended.
- `"1e" -> nil`
I'd consider this a current bug. We should probably consume `1` as `1.0` and then leave the `e` unconsumed.
Beyond those cases, there are things that `Double.init` parses that are …

Improve double parsing logic

---

Sources/Parsing/Parsers/Double.swift
Tests/ParsingTests/DoubleTests.swift

The parsing currently fails when the `"E"` is followed by a `"+"`, because the `"E"` is not dropped before checking for that character.

Fix parsing of floats with scientific notation

---

Sources/Parsing/Internal/Breakpoint.swift
Sources/Parsing/Parsers/Many.swift
Tests/ParsingTests/ManyTests.swift

Just exploring an alternative implementation to #73.
Some unanswered questions:
@tgrapperon @iampatbrown Thoughts?

Use memcmp to short-circuit Many when input isn't consumed

---

Sources/swift-parsing-benchmark/Routing.swift

- `Route` is pretty generic, so let's use the more domain-specific `AppRoute`
- `End` is also pretty generic. We've preferred the more descriptive `PathEnd`

Clean up routing example

---

Sources/Parsing/Internal/Deprecations.swift
Sources/Parsing/Parsers/Many.swift
Sources/Parsing/Parsers/Optional.swift
Sources/swift-parsing-benchmark/Routing.swift

A couple things I noticed.
- While `Upstream` works well in some contexts, in others I think we can be more specific.
- `PathEnd` in the routing example should probably _only_ check the path.

Cleanup: generic names, routing example

---

Sources/Parsing/Parsers/Int.swift

A couple small discoveries while going over various materials.
1. We have an erroneous version of `Int.parser` takes an explicit input type and ignores it.
2. We use `Radix: Self` in `Int.parser`, which means `Radix` would be `UInt8` for `UInt8.parser`, but `UInt8.init(_:radix:)` and the others use `Int` for the radix parameter, so let's clean this up.

`Int.parser` Fixes

---

README.md
Sources/Parsing/Parsers/Many.swift

This makes `Many.Separator` internally non-optional, which improves the performance of benchmarks using `Many`. I'm a lil puzzled, because I thought we made `Many.Separator` optional in the first place for performance reasons, but perhaps more recent versions of Swift have caused the inverse to be true. Or maybe we were just mistaken in the first place!

Improve `Many` performance

---

Tests/ParsingTests/CharacterSetTests.swift

- <s>Return nil when character set parser has no output</s>
- Add character set parsing tests
The rest of the test suite passes as well.
<s>Based on the [documentation](https://pointfreeco.github.io/swift-parsing/Parser/), my understanding is that a `CharacterSet`-based parser needs to return `nil` when the first character of its input isn't a member of the character set. </s>
I think there might be edge cases with non-ASCII characters that might be worth adding to tests, which I'm happy to do. Added some basic `CharacterSet` tests and tests for this specific change as a starter.

Add character set parser tests

---

Sources/Parsing/Builders/Variadics.swift
Sources/variadics-generator/VariadicsGenerator.swift
Tests/ParsingTests/ParserBuilderTests.swift

Added reversion to original if any parsers in `Zip` variations throw an error

---

.spi.yml

See https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/1541
Because of the three `configs:` sections we're only getting the `watchos` section when reading the `.spi.yml` file. That's why iOS and tvOS are failing :)

Remove extra `configs:`

---

Sources/Parsing/Parsers/Prefix.swift
Sources/swift-parsing-benchmark/JSON.swift
Tests/ParsingTests/ParsingErrorTests.swift
Tests/ParsingTests/PrefixTests.swift

We had a small bug in how the `Prefix` parser was consuming upon failure: it would always consume the minimum number of elements, which is more than the number of elements it actually consumed. This would produce bad error messages that point to the minimum successful position and _not_ the failure position.

Prefix should eagerly consume

---

Sources/Parsing/ParsingError.swift
Tests/ParsingTests/ManyTests.swift
Tests/ParsingTests/OneOfBuilderTests.swift
Tests/ParsingTests/OneOfTests.swift

In `ParsingError.debugDescription`, check for a `manyFailed` where all
the child errors are `ParsingError.failure` with the same
`originalInput` and `remainingInput` and no `underlyingError`s. In such
a scenario, only output the context once, for a more compact and legible
diagnostic.
Before:
error: multiple failures occurred
error: unexpected input
--> input:1:1
1 | president
| ^ expected "admin"
error: unexpected input
--> input:1:1
1 | president
| ^ expected "guest"
error: unexpected input
--> input:1:1
1 | president
| ^ expected "member"
After:
error: unexpected input
--> input:1:1
1 | president
| ^ expected "admin"
| ^ expected "guest"
| ^ expected "member"

coalesce manyFailed error messages

---

Sources/Parsing/Parser.swift
Tests/ParsingTests/ParserTests.swift

I think this is probably a good change. Swift has a nice way to expose incremental and non-incremental parser interfaces, so when incrementally parsing a collection we can fail if everything wasn't parsed.
This does mean certain parsers need to be more descriptive (_e.g._ add an explicit trailing parser to trim any extra space) but it could also potentially catch more issues.

Require parsing to end when using non-incremental parsing

---

Sources/Parsing/ParsingError.swift

`originalInput.base[…]` apparently now makes an `ArraySlice`, which is conflicting with the expected `Slice`. 
We can instantiate the `Slice` directly to avoid confusion.
This change should be backward-compatible.

Fix build failure on Xcode 13.3b3 - Swift 5.6

---

Sources/Parsing/Parsers/Not.swift
Sources/Parsing/Parsers/OneOfMany.swift
Tests/ParsingTests/NotTests.swift
Tests/ParsingTests/OneOfTests.swift
Tests/ParsingTests/ReplaceErrorTests.swift

After discussion from #149, we have a better handle on when and where a parser should backtrack. Basically: if a parser can recover from failure, it should backtrack to the `input`'s state before the failure occurred.
This means we can finesse the behavior of backtracking in the few parsers that need to consider it.
- `Optionally` — Not implemented in this PR, but we will merge #149 in soon!
- `replaceError(with:)` — This already had backtracking baked into it because it's a specialization of `OneOf`, though this PR adds a test.
- `Not` — This parser (along with `Peek`) _always_ backtracked, since they shouldn't consume input. But we think there's no reason for `Not` to _always_ backtrack. If it fails it should be safe enough to leave input consumed and rely on upstream `OneOf`s, etc., to …

Backtracking Finesse

---

README.md
Sources/Parsing/Documentation.docc/Articles/Backtracking.md
Sources/Parsing/Parser.swift

The DocC articles are now the source-of-truth for parser info, and so we can remove a bunch of duplicated info from the README and `Parser` docs.

Remove duplicate docs from README and Parser.

---

Makefile
README.md
Sources/Parsing/Documentation.docc/Articles/Backtracking.md
Sources/Parsing/Documentation.docc/Articles/Design.md
Sources/Parsing/Documentation.docc/Articles/ErrorMessages.md
Sources/Parsing/Documentation.docc/Articles/GettingStarted.md
Sources/Parsing/Documentation.docc/Articles/StringAbstractions.md
Sources/Parsing/Documentation.docc/Parsing.md

Since Xcode doesn't trim markdown files, let's automate this at the CI level.

Auto-trim trailing markdown whitespace

---

Sources/Parsing/Parsers/Peek.swift
Tests/ParsingTests/PeekTests.swift

No longer returns the matched peek value.
Adjusted backtracking behaviour to match new expectations
Added backtracking test.

Adjusted Peek

---

Sources/Parsing/Documentation.docc/Articles/Parsers/Bool.md
Sources/Parsing/Documentation.docc/Articles/Parsers/CharacterSet.md
Sources/Parsing/Documentation.docc/Articles/Parsers/Double.md
Sources/Parsing/Documentation.docc/Articles/Parsers/Float.md
Sources/Parsing/Documentation.docc/Articles/Parsers/Int.md
Sources/Parsing/Documentation.docc/Articles/Parsers/String.md
Sources/Parsing/Documentation.docc/Articles/Parsers/UUID.md
Sources/Parsing/Parsers/Not.swift
Sources/Parsing/Parsers/Peek.swift

Previous this kind of code can be compiled (while the original intention is not so), because Xcode can infer that the type is `Substring` by `.parse(".1.2")`.
```swift
try Parse {
Double.parser()
Double.parser() // 🛑 Ambiguous use of 'parser(of:)'
}
.parse(".1.2")
```
We can fix it like this:
```swift
let parser = Parse {
Double.parser()
Double.parser() // 🛑 Ambiguous use of 'parser(of:)'
}
try parser.parse(".1.2")
```

Fix recently updated docc files & added docs to Not and Peek

---

Sources/Parsing/Documentation.docc/Articles/Design.md
Sources/Parsing/Documentation.docc/Articles/ErrorMessages.md
Sources/Parsing/Documentation.docc/Articles/Parsers/Int.md
Sources/Parsing/Parsers/Int.swift
Sources/swift-parsing-benchmark/Color.swift
Sources/swift-parsing-benchmark/Date.swift

We chatted about this awhile back and was fresh in mind after submitting #177.
I think it's probably a good default for this particular parser, especially since we can currently construct nonsensical parsers like `UInt.parser(isSigned: true)`.
If we need a simple numeric parser that doesn't consider the sign, maybe we should have a dedicated `Digits` parser?

Remove `isSigned` config from `Int.parser()`

---

Sources/Parsing/Documentation.docc/Articles/Parsers/CaseIterable.md
Sources/Parsing/Parsers/CaseIterableRawRepresentable.swift
Tests/ParsingTests/CaseIterableRawRepresentableTests.swift

Backporting and updating this from another branch.

Add parser for case-iterable, string raw-representable values

---

Sources/Parsing/Parser.swift
Sources/Parsing/Parsers/Newline.swift
Sources/Parsing/Parsers/Whitespace.swift
Sources/swift-parsing-benchmark/JSON.swift
Tests/ParsingTests/OneOfTests.swift
Tests/ParsingTests/WhitespaceTests.swift

This changes `Whitespace` to be a bit more reasonable to use:
- It can now be configured to consume only horizontal _or_ vertical whitespace.
- It is now Unicode friendly
- It is now `Void`-returning (trivia can be useful, but isn't a great default; we'll have a solution to this breaking change in a future PR)

Whitespace(.horizontal) and Whitespace(.vertical)

---

Sources/Parsing/Parsers/Whitespace.swift

Following #185, I've completed the list of cases to match `CharacterSet.whitespace` and `CharacterSet.newlines`.
I've added 1 horizontal case (`U+1680`).
I've added 3 vertical cases (`U+000B`, `U+000C`, and `U+0085`).
For consistency, I've replaced `.init(ascii:)` occurrences with their corresponding hexadecimal literal value. I've also used hexadecimal literals instead of decimal when they match UTF-8 codepoints. I can switch to all decimal/hexadecimal if preferable.
I've also added a few comments to improve readability. 
I can reverse these last changes if needed.
I didn't add new tests as the current implementation isn't exhaustive either. I can add a few ones if needed.

Complete Whitespace cases

---

Sources/Parsing/Parsers/Pipe.swift
Tests/ParsingTests/PipeTests.swift

I was surprised to find a parser was succeeding because a parser pipe was happily discarding trailing input.
Calling the non-inout version of `.parse(string)` inserts an `End` parser automatically, and I think we should have similar behavior here. So this PR appends a `PipeEnd` parser to the end of a parser pipe when the input is a collection. `PipeEnd` is basically an `End` parser with custom error behavior.

Require pipes over collections of input to fully consume input

---

Sources/Parsing/ParserPrinters/Float.swift

This should fix #199.
The char range is checked to be in [A-Z] (that is `65...90`) before trying to lowercase the char by adding 32. 
This prevents going beyond `UInt8.max` by mistake.
I added a test that passed, but I removed it as it was only testing some internal method implementation.

Fix overflow when comparing non-alphabetical chars

---

Sources/Parsing/ParserPrinters/Pipe.swift
Tests/ParsingTests/PipeEndTests.swift

Added `ParserPrinter` conformance to the `PipeEnd` parser as discussed in #226

Make PipeEnd a ParserPrinter

---

Sources/Parsing/ParserPrinters/End.swift

Lowers the restriction on the End parser from Collection to Sequence.

lower restriction on End parser from Collection to Sequence

---

Sources/Parsing/ParserPrinters/Prefix.swift
Tests/ParsingTests/PrefixTests.swift

The printing for the `Prefix` `ParserPrinter` fails whenever it detects that the next element printed matches its predicate. However, this should be allowed in the special case that the parser _has a maximum count_, and _the value to print has exactly that count_. This is because that would have stopped the parsing before the next element, regardless of whether it matches the predicate or not.

Allow match after `Prefix` with max count

---

Sources/Parsing/Builders/OneOfBuilder.swift

Hello 👋  Hope all is well
The changes fix a small type for `OneOfBuilder.swift` documentation
I've took the example from [its tests](https://github.com/pointfreeco/swift-parsing/blob/main/Tests/ParsingTests/OneOfBuilderTests.swift)
```swift
final class OneOfBuilderTests: XCTestCase {
func testBuildArray() {
enum Role: String, CaseIterable, Equatable {
case admin
case guest
case member
}
let parser = OneOf {
for role in Role.allCases {
role.rawValue.map { role }
}
}
//...
```

Fix typo in OneOfBuilder documentation

---

Sources/Parsing/ParserPrinters/OneOfMany.swift

Hello 👋 
The changes fix a small typo in `OneOfMany.swift` documentation
Sorry for missing it in [my previous PR](https://github.com/pointfreeco/swift-parsing/pull/257) 🙇

Fix typo in OneOfMany documentation

---

Sources/Parsing/ParserPrinters/CaseIterableRawRepresentable.swift

#276
> Hi @ytyubox, good catch!
> 
> Rather than making the initializer public, what if we made the parser work with all `FixedWidthInteger` types? Then we could all the various integer types.
> 
> If you have the time you want to open a PR to do that? If not we can take care of it.

Extend CaseIterableRawRepresentable to FixedWidthInteger

---

Sources/Parsing/Documentation.docc/Articles/Backtracking.md
Sources/Parsing/ParserPrinters/Backtrack.swift
Sources/Parsing/ParserPrinters/Backtracking.swift
Sources/Parsing/ParserPrinters/OneOf.swift
Tests/ParsingTests/BacktrackTests.swift
Tests/ParsingTests/OneOfTests.swift

Due to the discussions in #286 we realized that there is no way to explicitly backtrack just a single parser since `OneOf` does not undo the consumption of the last parser run. We think we want to keep that behavior, but think also explicit backtracking can be good, so we are adding a dedicated `Backtrack` parser.

Add Backtrack parser.

---

Sources/Parsing/Internal/Deprecations.swift
Tests/ParsingTests/FromSubstringTests.swift

I'm trying to migrate old Parsing code that wasn't using `From(.substring)' etc. Like in #291 the @ParseBuilder should work on the converted input e.g. `Substring` for FromSubstring and not on the upstream input.

FromSubstring ParseBuilder needs Substring as Input

---

Sources/Parsing/ParserPrinters/Pipe.swift
Tests/ParsingTests/PipeTests.swift

I'm currently trying to migrate some parsing code to the 5.8 branch. I think I found a bug, but it could also be a misunderstanding with the latest changes.
The ParseBuilder is for Downstream so it should use it’s input. Or Upstream.Output as pipe runs the downstream parser on the output of the upstream parser. Which is why Upstream.Output == Downstream.Input.
With the 5.8 changes pipe uses the wrong input here. This only causes issues, if Upstream and Downstream have a different Input type.
The test can probably be simplified.

Downstream ParseBuilder should use Downstream.Input as Input

---

Sources/swift-parsing-benchmark/Date.swift

The offset in the timezone was mapping to minutes rather than seconds
```diff
let input = "1979-05-27T00:32:00+12:00"
let expected: DateComponents = .init(
-     timeZone: TimeZone(identifier: "GMT+0012"),
+     timeZone: TimeZone(identifier: "GMT+1200"),
year: 1979,
month: 5,
day: 27,
hour: 0,
minute: 32,
second: 0
)
```

Fix seconds mapping in Date benchmark

---

Package.resolved
README.md
Sources/swift-parsing-benchmark/Date.swift

Incorporates a helper from @juri's [parser](https://github.com/juri/Parse3339) to improve things in our demo a bit.
Benchmarked against Parse3339 [here](https://github.com/pointfreeco/swift-parsing/commit/fd4acb45111c9d696832d96023179cbe4adbc2a4) and it's nice to see how well the relatively naive combinators performed by comparison:
```
name                      time         std        iterations
------------------------------------------------------------
Date.Parser                3583.000 ns ±  18.18 %     355076
Date.Parse3339             3083.000 ns ±  19.16 %     448056
Date.DateFormatter        21708.000 ns ±   7.24 %      63634
Date.ISO8601DateFormatter 26958.000 ns ±   5.17 %      51322
```

Improve `Date` parser demo

---

Sources/Parsing/ParserPrinters/Prefix.swift

Removed documentation for an unused initializer parameter in the Prefix parser.

Fix the Prefix parser documentation

---

Parsing.playground/Contents.swift
Parsing.xcworkspace/xcshareddata/swiftpm/Package.resolved

Playground example had a compilation error due to some changes in Swift Parsing.
Using the ParsePrint with input initialiser fixes the problem
Related issue: https://github.com/pointfreeco/swift-parsing/issues/349

Fixed Playground compilation error

---

Sources/Parsing/ParserPrinters/PrefixThrough.swift
Sources/Parsing/ParserPrinters/PrefixUpTo.swift

I have made a simple HTML tokenizer and noticed using Instruments that `PrefixThrough` was spending a lot of time in `Substring.count`, which in turn was calling `distance(from:to:)`. I assume this is because the character count of a substring isn't known until calculated due to how Unicode works. This patch replaces the substring count check with a match end index check instead.
I was unable to make sense of the results from the benchmark app, but in my HTML project (link provided) there was a substantial speedup. In that repo there is a benchmark app in the branch `swift-parsing`, and you can switch between swift-parsing versions in `Package.swift`.
https://github.com/BjornRuud/HTMLLexer.git

Don't use input.count in PrefixThrough and PrefixUpTo for speedup.

---

Sources/Parsing/Builders/OneOfBuilder.swift
Sources/Parsing/ParserPrinters/Printing.swift

The most important change is '123 ' --> ' 123' (the whitespace is in front, not behind).
That was quite misleading 😃

Fix a mistake in docs

---

Sources/Parsing/Builders/ParserBuilder.swift
Tests/ParsingTests/ParserBuilderTests.swift

Fixes printing of parameter pack-combined parser builders.

Attempt to safely bit-cast for printing of parameter packs
